import { typo } from "lib";

export const dataTableConfig = {
  textOperators: [
    { label: typo("Содержит"), value: "iLike" as const },
    { label: typo("Не содержит"), value: "notILike" as const },
    { label: typo("Равно"), value: "eq" as const },
    { label: typo("Не равно"), value: "ne" as const },
    { label: typo("Пусто"), value: "isEmpty" as const },
    { label: typo("Не пусто"), value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: typo("Равно"), value: "eq" as const },
    { label: typo("Не равно"), value: "ne" as const },
    { label: typo("Меньше"), value: "lt" as const },
    { label: typo("Меньше или равно"), value: "lte" as const },
    { label: typo("Больше"), value: "gt" as const },
    { label: typo("Больше или равно"), value: "gte" as const },
    { label: typo("В диапазоне"), value: "isBetween" as const },
    { label: typo("Пусто"), value: "isEmpty" as const },
    { label: typo("Не пусто"), value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: typo("Равно"), value: "eq" as const },
    { label: typo("Не равно"), value: "ne" as const },
    { label: typo("Раньше"), value: "lt" as const },
    { label: typo("Позже"), value: "gt" as const },
    { label: typo("Не позже"), value: "lte" as const },
    { label: typo("Не раньше"), value: "gte" as const },
    { label: typo("В диапазоне"), value: "isBetween" as const },
    { label: typo("Относительно сегодня"), value: "isRelativeToToday" as const },
    { label: typo("Пусто"), value: "isEmpty" as const },
    { label: typo("Не пусто"), value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: typo("Равно"), value: "eq" as const },
    { label: typo("Не равно"), value: "ne" as const },
    { label: typo("Пусто"), value: "isEmpty" as const },
    { label: typo("Не пусто"), value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: typo("Хотя бы одно из"), value: "inArray" as const },
    { label: typo("Ни одно из"), value: "notInArray" as const },
    { label: typo("Пусто"), value: "isEmpty" as const },
    { label: typo("Не пусто"), value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: typo("Равно"), value: "eq" as const },
    { label: typo("Не равно"), value: "ne" as const },
  ],
  sortOrders: [
    { label: typo("По возрастанию"), value: "asc" as const },
    { label: typo("По убыванию"), value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
    "categoryTreeMultiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};

export type DataTableConfig = typeof dataTableConfig;
