import {
  Award,
  BadgeCheck,
  Clock,
  Cog,
  Factory,
  Flame,
  Gauge,
  Hammer,
  Handshake,
  HardHat,
  Layers,
  type LucideIcon,
  MapPin,
  PackageCheck,
  Ruler,
  Settings,
  ShieldCheck,
  Sparkles,
  Thermometer,
  Timer,
  Truck,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

import type { CardIconKey } from "~/sections/schema";

/** Реестр иконок секции «карточки»; satisfies гарантирует покрытие всех ключей схемы. */
export const cardIcons = {
  award: Award,
  badgeCheck: BadgeCheck,
  clock: Clock,
  cog: Cog,
  factory: Factory,
  flame: Flame,
  gauge: Gauge,
  hammer: Hammer,
  handshake: Handshake,
  hardHat: HardHat,
  layers: Layers,
  mapPin: MapPin,
  packageCheck: PackageCheck,
  ruler: Ruler,
  settings: Settings,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  thermometer: Thermometer,
  timer: Timer,
  truck: Truck,
  users: Users,
  wrench: Wrench,
  zap: Zap,
} as const satisfies Record<CardIconKey, LucideIcon>;
